### ISSUE TITLE
`cirrusSearchElasticaWrite` errors when using `docker-compose.yml`

### ISSUE THREAD

**Issue by persona0591** [wmde/wikibase-release-pipeline#295]
Hi all,

I'm trying to run Wikibase using the (minimal) [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) example file. This is working perfectly.

However, if I add an item to Wikibase and then inspect the log output of the Docker containers, I see quite a number of log lines from the `wikibase_jobrunner_1`, related to `cirrusSearchElasticaWrite`. For example:

`error=ElasticaWrite job failed: Requeued`

and:

`error=ElasticaWrite job failed: Dropped`

These errors seem to be related to Elasticsearch. However, as far as I can see the `docker-compose.yml` example file doesn't contain an Elasticsearch image. Is there a way to fix the `cirrusSearchElasticaWrite` errors?

Thanks!

**Comment by toban** [comment]
Hello,

I suspect this was caused by the issue identified in https://github.com/wmde/wikibase-release-pipeline/issues/296

Feel free to close this issue if so or respond if it persists.

**Comment by persona0591** [comment]
hi @toban, thanks!

The issue persists: if I start a minimal Wikibase, using the [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) example file (so without Elasticsearch), and add a new item, then the job runner outputs messages like:

```
cirrusSearchElasticaWrite Special: method=sendData arguments=["content",[{"data":{"version":2,"wiki":"my_wiki","namespace":120,"namespace_text":"Item","title":"Q1","timestamp":"2022-01-14T15:56:08Z","create_timestamp":"2022-01-14T15:56:08Z","redirect":[]},"params":{"_id":"2","_type":"","_index":"","_cirrus_hints":{"BuildDocument_flags":0,"noop":{"version":"documentVersion"}}},"upsert":true}]] cluster=default createdAt=1642175779 errorCount=4 retryCount=0 requestId=afa7f00069eb1fae00c77188 namespace=-1 title= (id=10,timestamp=20220114155623) t=84 error=ElasticaWrite job failed: Dropped
```

I looks like the minimal Wikibase assumes Elasticsearch is running? Is there a way to tell the job runner to not start a job for updating Elasticsearch?

**Comment by toban** [comment]
> hi @toban, thanks!
> 
> The issue persists: if I start a minimal Wikibase, using the [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) example file (so without Elasticsearch), and add a new item, then the job runner outputs messages like:
> 
> ```
> cirrusSearchElasticaWrite Special: method=sendData arguments=["content",[{"data":{"version":2,"wiki":"my_wiki","namespace":120,"namespace_text":"Item","title":"Q1","timestamp":"2022-01-14T15:56:08Z","create_timestamp":"2022-01-14T15:56:08Z","redirect":[]},"params":{"_id":"2","_type":"","_index":"","_cirrus_hints":{"BuildDocument_flags":0,"noop":{"version":"documentVersion"}}},"upsert":true}]] cluster=default createdAt=1642175779 errorCount=4 retryCount=0 requestId=afa7f00069eb1fae00c77188 namespace=-1 title= (id=10,timestamp=20220114155623) t=84 error=ElasticaWrite job failed: Dropped
> ```
> 
> I looks like the minimal Wikibase assumes Elasticsearch is running? Is there a way to tell the job runner to not start a job for updating Elasticsearch?

Hello again, 

Yes this is to be expected unless you comment out the `MW_ELASTIC_HOST` variable in your `.env` file. This variable is read at runtime and determines if ElasticSearch is enabled or not. The decision to have this enabled by default is because with the removal of the `wb_terms` table case insensitive search and search by aliases etc doesn't work for 1.36 and up.

I've added a comment in the [template file](https://github.com/wmde/wikibase-release-pipeline/blob/main/example/template.env#L50) that will be updated once we do the next release

**Comment by toban** [comment]
> hi @toban, thanks!
> 
> The issue persists: if I start a minimal Wikibase, using the [docker-compose.yml](https://github.com/wmde/wikibase-release-pipeline/blob/wmde.3/example/docker-compose.yml) example file (so without Elasticsearch), and add a new item, then the job runner outputs messages like:
> 
> ```
> cirrusSearchElasticaWrite Special: method=sendData arguments=["content",[{"data":{"version":2,"wiki":"my_wiki","namespace":120,"namespace_text":"Item","title":"Q1","timestamp":"2022-01-14T15:56:08Z","create_timestamp":"2022-01-14T15:56:08Z","redirect":[]},"params":{"_id":"2","_type":"","_index":"","_cirrus_hints":{"BuildDocument_flags":0,"noop":{"version":"documentVersion"}}},"upsert":true}]] cluster=default createdAt=1642175779 errorCount=4 retryCount=0 requestId=afa7f00069eb1fae00c77188 namespace=-1 title= (id=10,timestamp=20220114155623) t=84 error=ElasticaWrite job failed: Dropped
> ```
> 
> I looks like the minimal Wikibase assumes Elasticsearch is running? Is there a way to tell the job runner to not start a job for updating Elasticsearch?

Hey, thanks for the report.

I tried this out and yeah CirrusSearch seems to queue up jobs even though it's not set to be used by `$wgSearchType`, only seems to be required for the extension to be enabled, not sure if this could be considered as a bug in CirrusSearch or just a quirk. I checked and this seems to be the case for all releases so far, even though it probably went unnoticed because of the jobs being ran on-request before the job-runner.

As this doesn't really break anything it just adds a bit of overhead for the jobs being retried by the default value of `wgCirrusSearchUpdateConflictRetryCount = 5;`

However, a work-around until we have a new release out is that you can also disable CirrusSearch completely by mounting an empty `CirrusSearch.php` file into the container if you create that in your `example/` folder.

`example/CirrusSearch.php`
```php
<php
// nothing here
```

`example/docker-compose.yml`
```yml
volumes:
    - ./CirrusSearch.php:/var/www/html/LocalSettings.d/CirrusSearch.php
```

In general it's recommended to run ElasticSearch alongside Wikibase for versions after 1.36 where the `wb_terms` table has been removed and no-longer supports case-insensitive search etc.

I hope this helps.

**Comment by toban** [comment]
Created a phabricator task to include this in the next release.

https://phabricator.wikimedia.org/T299393

**Comment by persona0591** [comment]
Hi @toban , thank you very much -- this clarifies and helps! Much appreciated.

**Comment by persona0591** [comment]
I'm closing this issue.
