### ISSUE TITLE
Wikibase: Quick-statements behind reverse proxy

### ISSUE THREAD

**Issue by D063520** [wmde/wikibase-release-pipeline#354]
Please refer to this Phabricator ticket: https://phabricator.wikimedia.org/T315916

**Comment by D063520** [comment]
@toban: Hi! Can you give a look at this?

**Comment by addshore** [comment]
Closing this as there is a comment on phab

**Comment by D063520** [comment]
is this suppose to work in the new version?

**Comment by ross-spencer** [comment]
> but let's keep the discussion on phabricator!

Have you considered disabling GH issues?  I personally comment on here because it's a lower barrier, but engagement is pretty low if not entirely non-existent at times. Phabricator isn't mentioned on the README at all. Perhaps that could be added, and if Issues can't  be closed down, an Issues template could point folks there.
