### ISSUE TITLE
Met problem installing WikibaseLexeme Extension

### ISSUE THREAD

**Issue by Kenan-jeff-Jiang** [wmde/wikibase-release-pipeline#756]
<img width="1512" alt="Screenshot 2024-08-25 at 12 08 47 PM" src="https://github.com/user-attachments/assets/89ccefa4-26cb-4614-9047-6d8fbe5495a8">

Hi, community,
I encountered a problem when I tried to install the WikibaseLexeme Extension to my local wikibase in docker. I did my wikibase set up following the official https://github.com/wmde/wikibase-release-pipeline/tree/main/deploy#initial-setup
and my extension setup with this https://www.mediawiki.org/wiki/Extension:WikibaseLexeme#:~:text=The%20Wikibase%20Lexeme%20extension%20provides,and%20mappings%20to%20other%20vocabularies.

From the error message, I think the wikibase has noticed this new extension and trying to load it. But it has a version mismatch.
I hope to get some help on the best step forward. Should I and how to upgrade the wikibase to 1.43? or is it possible to get an Lexeme extension that supports lower version of Wikibase. Many thanks.

**Comment by Superraptor** [comment]
Not directly related, but I had been trying to get extensions to work and have been documenting my attempts here: https://phabricator.wikimedia.org/T372599

**Comment by Kenan-jeff-Jiang** [comment]
I have decided to upgrade my wikibase to a version that is >= 1.43.  Based on the document, we have a list of remote branches:
  origin/HEAD -> origin/main
  origin/T296812-document-storage-locations
  origin/T363103-example-preflight-check
  origin/T367476-turn-rest-api-on
  origin/T372455-wbs-only-expose-proxy-ports
  origin/T372458-self-hosted-runners
  origin/auth-docker-hub
  origin/deploy-1
  origin/deploy-2
  origin/deploy-3
  origin/deploy-config-tidy
  origin/docker-compose-building-tagging
  origin/docker-compose-building-tagging--extended
  origin/ensure-correct-permissions-of-composer.local.json
  origin/healthchecks-to-dockerfiles
  origin/main
  origin/mw-1.39
  origin/mw-1.40
  origin/mw-1.41
  origin/nx-monorepo-non-js
  origin/nx-monorepo-non-js--test-maintenance
  origin/nx-monorepo-non-js--update-commits-ts
  origin/optional-certs
  origin/updated-release-checklist
  origin/wdqs-image-clean-up
  
  Current the `deploy-3` is the 1.42 version, I wonder which one is 1.43?

**Comment by rti** [comment]
Hi @Kenan-jeff-Jiang,

Thanks for contacting us.

I just added instructions how to install WikibaseLexeme to the ticket @Superraptor mentioned earlier already: https://phabricator.wikimedia.org/T372599

Wikibase Suite only supports stable MediaWiki versions. At the time of this writing, [the latest stable is 1.42](https://www.mediawiki.org/wiki/Version_lifecycle). Wikibase Suite is currently based on MediaWiki 1.42 on the `deploy-3` branch as well as the `main` branch. I would highly encourage you to stick to the stable version. We cannot support you with unreleased versions. In order to get compatible versions of extensions, make sure to checkout the `REL1_42` branch such as https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/WikibaseLexeme/+/refs/heads/REL1_42.

Hope that helps,
Best,
Robert

**Comment by rti** [comment]
I will close the issue for now. Feel free to reopen when you have further questions.
